name: media

services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/bruno/qbittorrent/config:/config
      - /mnt/zimacube/Downloads/torrents:/downloads
    ports:
      - '8080:8080'
      - '62609:62609'
