{
 "title": "CITOOLS Infrastructure",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Disk Capacity Current Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"citools\"}/kubelet_volume_stats_capacity_bytes{namespace=\"citools\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Disk Capacity Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"citools\"}/kubelet_volume_stats_capacity_bytes{namespace=\"citools\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "CITOOLS Memory Limit Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.pod_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [
       "resource.label.namespace_name",
       "=",
       "citools",
       "AND",
       "metadata.system_labels.top_level_controller_type",
       "=~",
       "Deployment|StatefulSet",
       "AND",
       "resource.label.container_name",
       "!=",
       "istio-proxy"
      ],
      "groupBys": [ "resource.label.pod_name" ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/limit_utilization",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "ci-cd-bv",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "CITOOLS CPU Limit Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.pod_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [
       "resource.label.namespace_name",
       "=",
       "citools",
       "AND",
       "metadata.system_labels.top_level_controller_type",
       "=~",
       "Deployment|StatefulSet",
       "AND",
       "resource.label.container_name",
       "!=",
       "istio-proxy"
      ],
      "groupBys": [ "resource.label.pod_name" ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/limit_utilization",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "ci-cd-bv",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Jenkins Agents Memory Limit Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.pod_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [
       "resource.label.namespace_name",
       "=",
       "jenkins-agents",
       "AND",
       "resource.label.container_name",
       "!=",
       "istio-proxy"
      ],
      "groupBys": [ "resource.label.pod_name" ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/limit_utilization",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "ci-cd-bv",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Jenkins Agents CPU Limit Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.pod_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [
       "resource.label.namespace_name",
       "=",
       "jenkins-agents",
       "AND",
       "resource.label.container_name",
       "!=",
       "istio-proxy"
      ],
      "groupBys": [ "resource.label.pod_name" ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/limit_utilization",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "ci-cd-bv",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  }
 ]
}