{
 "title": "OpenShift Cluster - CPU Usage By Region",
 "tags": [ "openshift" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "NodeCNS", "query": "label_values(instance)" },
   { "name": "NodeMaster", "query": "label_values(instance)" },
   { "name": "NodeApp", "query": "label_values(instance)" },
   { "name": "NodeInfra", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "App/Worker Nodes Memory Usage by Region",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU usage - Region: CNS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$NodeCNS$\"}[2m])) / sum (machine_cpu_cores{instance=~\"^$NodeCNS$\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU usage - Region: Master",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$NodeMaster$\"}[2m])) / sum (machine_cpu_cores{instance=~\"^$NodeMaster$\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU usage - Region: Apps",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$NodeApp$\"}[2m])) / sum (machine_cpu_cores{instance=~\"^$NodeApp$\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU usage - Region: Infra",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$NodeInfra$\"}[2m])) / sum (machine_cpu_cores{instance=~\"^$NodeInfra$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{id=\"/\",instance=~\".*cns.*\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{instance=~\".*cns.*\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{id=\"/\",instance=~\".*osm.*\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{instance=~\".*osm.*\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{id=\"/\",instance=~\".*osa.*\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{instance=~\".*osa.*\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{id=\"/\",instance=~\".*osi.*\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{instance=~\".*osi.*\"})"
    }
   ]
  },
  {
   "title": "CPU usage Masters",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate (container_cpu_usage_seconds_total{instance=~\".*osm.*\"}[2m])) * 100 ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU usage Apps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate (container_cpu_usage_seconds_total{id=\"/\",instance=~\".*osa.*\"}[2m])) * 100 ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU usage Storage CNS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate (container_cpu_usage_seconds_total{instance=~\".*cns.*\"}[2m])) * 100 ",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}