{
 "title": "Namespace Use",
 "tags": [
  "kubernetes",
  "openshift"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Namespace", "query": "label_values(namespace)" },
   { "name": "Node" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage - Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum (irate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",namespace=~\"^$Namespace$\"}[2m])) by (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Usage - Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum (irate(container_memory_working_set_bytes{namespace=~\"^$Namespace$\"}[2m])) by (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Usage - PODs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum (container_memory_working_set_bytes{namespace=~\"^$Namespace$\"}) by (pod_name, namespace))",
     "legendFormat": "POD: {{ pod_name }} | {{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Usage - PODs ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum (rate (container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])) by (pod_name, namespace))",
     "legendFormat": "POD: {{ pod_name }} | {{ namespace }}"
    }
   ]
  }
 ]
}