{
 "title": "OpenShift Pods Usage",
 "tags": [
  "kubernetes",
  "openshift"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Sessões por Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_backend_current_sessions{namespace=~\"^$Namespace$\"}) by (route, namespace)  ",
     "legendFormat": "{{ route }} | {{ namespace }}"
    }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container_name!=\"POD\",namespace=~\"^$Namespace$\"} != 0 ) by (namespace, pod_name) ",
     "legendFormat": "{{ pod_name}}  |  {{ namespace }}"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\",kubernetes_io_hostname=~\"^.*$\"}[2m])) by (pod_name, namespace)",
     "legendFormat": "{{ pod_name }} | {{ namespace }}"
    }
   ]
  }
 ]
}