{
 "title": "Spinnaker Infrastructure",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Spinnaker CPU Limit Utilization",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.container_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [
       "resource.label.namespace_name",
       "=",
       "spinnaker",
       "AND",
       "resource.label.container_name",
       "!=",
       "istio-proxy",
       "AND",
       "resource.label.container_name",
       "!=",
       "monitoring-daemon",
       "AND",
       "metadata.system_labels.top_level_controller_type",
       "=",
       "Deployment"
      ],
      "groupBys": [
       "resource.label.container_name",
       "resource.label.pod_name"
      ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/limit_utilization",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "ci-cd-bv",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Spinnaker Memory Limit Utilization",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.container_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [
       "resource.label.namespace_name",
       "=",
       "spinnaker",
       "AND",
       "resource.label.container_name",
       "!=",
       "istio-proxy",
       "AND",
       "resource.label.container_name",
       "!=",
       "monitoring-daemon",
       "AND",
       "metadata.system_labels.top_level_controller_type",
       "=",
       "Deployment"
      ],
      "groupBys": [
       "resource.label.container_name",
       "resource.label.pod_name"
      ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/limit_utilization",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "ci-cd-bv",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Kubernetes Node Allocatable CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.node_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [],
      "groupBys": [ "resource.label.node_name" ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/cpu/allocatable_utilization",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "ci-cd-bv",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Kubernetes Node Allocatable Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.node_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [],
      "groupBys": [ "resource.label.node_name" ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/memory/allocatable_utilization",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "ci-cd-bv",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Spinnaker monitoring-daemon CPU Limit Utilization",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.pod_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [
       "resource.label.namespace_name",
       "=",
       "spinnaker",
       "AND",
       "resource.label.container_name",
       "=",
       "monitoring-daemon",
       "AND",
       "metadata.system_labels.top_level_controller_type",
       "=",
       "Deployment"
      ],
      "groupBys": [
       "resource.label.container_name",
       "resource.label.pod_name"
      ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/limit_utilization",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "ci-cd-bv",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Spinnaker monitoring-daemon Memory Limit Utilization",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.pod_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [
       "resource.label.namespace_name",
       "=",
       "spinnaker",
       "AND",
       "resource.label.container_name",
       "=",
       "monitoring-daemon",
       "AND",
       "metadata.system_labels.top_level_controller_type",
       "=",
       "Deployment"
      ],
      "groupBys": [
       "resource.label.container_name",
       "resource.label.pod_name"
      ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/limit_utilization",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "ci-cd-bv",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  }
 ]
}